package com.demo.homeloanapp.entity;

public enum Status {

	PENDING ,
	APPROVED,
	WAITAING_FOR_FINANCE_APPROVAL,
	WAITING_FOR_LAND_VARIFICATION_OFFICE_APPROVAL,
	REJECTED,
	DOCCUMENT_NOT_APPLOADED,
	DOCCUMENT_UPLOADED;
}
